### ISSUE TITLE
No animations when opening file

### ISSUE THREAD

**Issue by Akxe** [m00s/angular-photoswipe#9]
I don't know if it is only me, but I don't see any animations, and it is a bit disturbing, sice that is one of main reasons, why I wanted PhotoSwipe. (in demo)

**Comment by erikamello** [comment]
I had the same problem and I figured out that this happens because getThumbBoundsFn in options is not defined. I believe this is something that could be implemented in the directive since it needs to manipulate the DOM to find the thumbnails position.

My suggestion is to add something like this before instantiating a new PhotoSwipe (line 51):

``` javascript
if (!scope.options.getThumbBoundsFn) {
              scope.options.getThumbBoundsFn = function (index) {                  
                  var thumbnail = document.querySelectorAll('.img-thumbnail')[index];
                  var pageYScroll = window.pageYOffset || document.documentElement.scrollTop;
                  var rect = thumbnail.getBoundingClientRect();
                  return { x: rect.left, y: rect.top + pageYScroll, w: rect.width };
              };
          } 
```

Where '.img-thumbnail' is the selector for your thumbnails. This could possibly be another attribute of the directive.

**Comment by hirbod** [comment]
While this is working fine when you only have one gallery, how to go on with multiple ones?

There is an official doc about that:
http://photoswipe.com/documentation/getting-started.html#dom-to-slide-objects

and a working example:
http://codepen.io/dimsemenov/pen/ZYbPJM

But I really don't have a clue right now, how to use this with this directive. Any guesses? Maybe @m00s ?

**Comment by m00s** [comment]
I have the @gabrielchites solution working in local, and I'll push it soon.
